### ISSUE TITLE
TileCutter location on Linux

### ISSUE THREAD

**Issue by MatthewForrester** [An-dz/tilecutter#11]
I am trying to install and run TileCutter on Linux, but so far without success.

Distro: Kubuntu 22.04
Python: 3.10.6
wxPython: wxpython-tools 4.0.7+dfsg-13build1
NumPy: python3-numpy 1.21.5-1ubuntu22.04.1

Based on the output below, TileCutter seem to have some assumptions about where it is installed and maybe that your Simutrans (user?) directory is in ~/Documents/Simutrans.

If you could mention in the installation instructions where TileCutter should be installed, then I will happily move it there. 

Does it rely on the presence of files from Simutrans Standard to run? I only install Standard through Steam. If it needs those files in a certain place, then again it would be helpful to know.

EDIT: Actually, looking at the output more closely, I think that it may have been unable to handle a space in the path in the path to the installation directory.

**Output of ./install.sh**
```
chmod: cannot access '/mnt/house/linmanfu/Documents/Simutrans': No such file or directory
chmod: cannot access 'Development/tilecutter/TileCutter.desktop': No such file or directory`
Do you want a Start Menu item? (y/N) n

You can now run TileCutter by double-clicking the TileCutter
icon on the same directory of this installation file.
```

**Output of running TileCutter shortcut:**
```
Could not find the program '/mnt/house/linmanfu/Documents/Simutrans
```

(I'm not sure whether it was looking for Simutrans or whether it was thrown the fact that it was originally installed in a directory called "Simutrans Development", with a space in the directory name)

**Output of running ./libs/TileCutter.pyw from terminal:**
```
TileCutter : INFO TC:WX version is: 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5: main.<module>
TileCutter : INFO TC:Begin loading translation from file: languages/tc_gr.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_dk.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_es.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_ja.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_fi.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_it.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_hr.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_ce.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_id.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_et.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_ru.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_nl.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_ro.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_sv.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_en.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_no.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_hu.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_cz.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_pt.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_de.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_pl.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_zh.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_ko.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_sk.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_tr.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_cn.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_lt.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_fr.tab: translator.__init__
TileCutter : INFO TC:Begin loading translation from file: languages/tc_ca.tab: translator.__init__
TileCutter : INFO TC:Language setting found in config file - Setting active translation to English: translator.__init__
TileCutter : INFO TC:configuration source is unix auto location: main.<module>
TileCutter : INFO TC:configuration loaded from file: /home/matthew/.tilecutter/tilecutter.config: main.<module>
TileCutter : DEBUG TC:{'debug_on': True, 'debug_level': 2, 'logfile': '/home/matthew/.tilecutter/tilecutter.log', 'logfile_platform_default': True, 'transparent': [231, 255, 255], 'transparent_bg': [[153, 153, 153], [103, 103, 103]], 'default_paksize': 64, 'valid_image_extensions': ['.png'], 'OFFSET_NEGATIVE_ALLOWED': False, 'window_size': [-1, -1], 'window_position': [-1, -1], 'window_maximised': False, 'last_save_path': '', 'last_image_path': '', 'negative_offset_allowed': False, 'default_image_path': '', 'path_to_makeobj': '', 'write_dat': True, 'default_language': 'English'}: main.<module>
TileCutter : DEBUG TC:sys.argv says: ['./libs/tilecutter.pyw']: main.run
TileCutter : INFO TC:options: {'pak_output': False, 'dat_output': True, 'cli': False, 'png_directory': None, 'png_filename': None, 'dat_directory': None, 'dat_filename': None, 'pak_directory': None, 'pak_filename': None, 'verbose': None}: main.run
TileCutter : INFO TC:args: []: main.run
TileCutter : INFO TC:Init - Creating app with GUI: main.run
TileCutter : INFO TC:Starting...: main.OnInit
TileCutter : INFO TC:Create default project: main.OnInit
TileCutter : DEBUG TC:as: <bound method Project.save_location of <project.Project object at 0x7fa506494df0>>, datfile_location: <bound method Project.datfile_location of <project.Project object at 0x7fa506494df0>>, pngfile_location: <bound method Project.pngfile_location of <project.Project object at 0x7fa506494df0>>, pakfile_location: <bound method Project.pakfile_location of <project.Project object at 0x7fa506494df0>>: project.init_save_location
TileCutter : INFO TC:New title text: main.update_title_text
TileCutter : DEBUG TC:Check Project for changes - Project Unchanged: project.has_changed
TileCutter : DEBUG TC:Setting title_text to: (New Project) - TileCutter: main.update_title_text
TileCutter : INFO TC:Show main frame: main.OnInit
TileCutter : INFO TC:Creating main frame: viewMain.__init__
TileCutter : INFO TC:Creating menu: menuObject.__init__
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Adding item: menuObject.add_menu_item
TileCutter : INFO TC:Translating Menu: menuObject.translate
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Create season controls: controlSeason.__init__
TileCutter : INFO TC:Creating image controls: controlImage.__init__
TileCutter : INFO TC:Creating facing direction controls: controlFacing.__init__
TileCutter : INFO TC:Create dimension controls: controlDims.__init__
TileCutter : INFO TC:Creating offset controls: controlOffset.__init__
TileCutter : INFO TC:Create image display area: viewImage.__init__
TileCutter : INFO TC:Creating image location controls: controlImageFile.__init__
TileCutter : INFO TC:Create file picker: filePicker.__init__
TileCutter : INFO TC:Translate UI: viewImage.translate
TileCutter : INFO TC:Translate UI: controlImageFile.translate
TileCutter : INFO TC:Creating files locations controls: controlFiles.__init__
TileCutter : INFO TC:Create file picker: filePicker.__init__
TileCutter : INFO TC:Translate UI: viewMain.translate
TileCutter : INFO TC:Translate UI: viewImage.translate
TileCutter : INFO TC:Translate UI: controlImageFile.translate
TileCutter : INFO TC:Translate UI: controlSeason.translate
TileCutter : INFO TC:Translate UI: controlImage.translate
TileCutter : INFO TC:Translate UI: controlFacing.translate
TileCutter : INFO TC:Translate UI: controlDims.translate
TileCutter : INFO TC:Translate UI: controlOffset.translate
TileCutter : INFO TC:Translate UI: controlFiles.translate
TileCutter : INFO TC:Translating Menu: menuObject.translate
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Keyboard shortcuts: menuObject.gsc
TileCutter : INFO TC:Set new title text: viewMain.set_title
TileCutter : DEBUG TC:previous panel size: (877, 797), previous window size: (877, 850): viewMain.translate
TileCutter : DEBUG TC:minimum panel size is: (877, 797): viewMain.translate
TileCutter : DEBUG TC:new panel size is: (877, 797), new window size is: (877, 850): viewMain.translate
Traceback (most recent call last):
  File "/mnt/house/linmanfu/simutrans/tilecutter/libs/main.py", line 86, in OnInit
    self.frame = tcui.ViewMain(None, self, wx.ID_ANY, "TileCutter")
  File "/mnt/house/linmanfu/simutrans/tilecutter/libs/tcui/viewMain.py", line 153, in __init__
    self.translate()
  File "/mnt/house/linmanfu/simutrans/tilecutter/libs/tcui/viewMain.py", line 233, in translate
    self.panel.SetMinSize(wx.Size(max(self.panel.GetBestSize().Get()[1] * 1.4, self.panel.GetBestSize().Get()[0]), self.panel.GetBestSize().Get()[1]))
TypeError: Size(): arguments did not match any overloaded call:
  overload 1: too many arguments
  overload 2: argument 1 has unexpected type 'float'
  overload 3: argument 1 has unexpected type 'float'
OnInit returned false, exiting...
```

**Comment by MatthewForrester** [comment]
GitHub is refusing to allow me to attach TileCutter.log, so here are the contents:

```
INFO	main.<module>: WX version is: 4.0.7 gtk3 (phoenix) wxWidgets 3.0.5
INFO	translator.__init__: Begin loading translation from file: languages/tc_gr.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_dk.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_es.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_ja.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_fi.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_it.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_hr.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_ce.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_id.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_et.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_ru.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_nl.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_ro.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_sv.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_en.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_no.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_hu.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_cz.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_pt.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_de.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_pl.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_zh.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_ko.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_sk.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_tr.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_cn.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_lt.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_fr.tab
INFO	translator.__init__: Begin loading translation from file: languages/tc_ca.tab
INFO	translator.__init__: Language setting found in config file - Setting active translation to English
INFO	main.<module>: configuration source is unix auto location
INFO	main.<module>: configuration loaded from file: /home/matthew/.tilecutter/tilecutter.config
DEBUG	main.<module>: {'debug_on': True, 'debug_level': 2, 'logfile': '/home/matthew/.tilecutter/tilecutter.log', 'logfile_platform_default': True, 'transparent': [231, 255, 255], 'transparent_bg': [[153, 153, 153], [103, 103, 103]], 'default_paksize': 64, 'valid_image_extensions': ['.png'], 'OFFSET_NEGATIVE_ALLOWED': False, 'window_size': [-1, -1], 'window_position': [-1, -1], 'window_maximised': False, 'last_save_path': '', 'last_image_path': '', 'negative_offset_allowed': False, 'default_image_path': '', 'path_to_makeobj': '', 'write_dat': True, 'default_language': 'English'}
DEBUG	main.run: sys.argv says: ['./libs/tilecutter.pyw']
INFO	main.run: options: {'pak_output': False, 'dat_output': True, 'cli': False, 'png_directory': None, 'png_filename': None, 'dat_directory': None, 'dat_filename': None, 'pak_directory': None, 'pak_filename': None, 'verbose': None}
INFO	main.run: args: []
INFO	main.run: Init - Creating app with GUI
INFO	main.OnInit: Starting...
INFO	main.OnInit: Create default project
DEBUG	project.init_save_location: as: <bound method Project.save_location of <project.Project object at 0x7fa506494df0>>, datfile_location: <bound method Project.datfile_location of <project.Project object at 0x7fa506494df0>>, pngfile_location: <bound method Project.pngfile_location of <project.Project object at 0x7fa506494df0>>, pakfile_location: <bound method Project.pakfile_location of <project.Project object at 0x7fa506494df0>>
INFO	main.update_title_text: New title text
DEBUG	project.has_changed: Check Project for changes - Project Unchanged
DEBUG	main.update_title_text: Setting title_text to: (New Project) - TileCutter
INFO	main.OnInit: Show main frame
INFO	viewMain.__init__: Creating main frame
INFO	menuObject.__init__: Creating menu
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.add_menu_item: Adding item
INFO	menuObject.translate: Translating Menu
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	controlSeason.__init__: Create season controls
INFO	controlImage.__init__: Creating image controls
INFO	controlFacing.__init__: Creating facing direction controls
INFO	controlDims.__init__: Create dimension controls
INFO	controlOffset.__init__: Creating offset controls
INFO	viewImage.__init__: Create image display area
INFO	controlImageFile.__init__: Creating image location controls
INFO	filePicker.__init__: Create file picker
INFO	viewImage.translate: Translate UI
INFO	controlImageFile.translate: Translate UI
INFO	controlFiles.__init__: Creating files locations controls
INFO	filePicker.__init__: Create file picker
INFO	viewMain.translate: Translate UI
INFO	viewImage.translate: Translate UI
INFO	controlImageFile.translate: Translate UI
INFO	controlSeason.translate: Translate UI
INFO	controlImage.translate: Translate UI
INFO	controlFacing.translate: Translate UI
INFO	controlDims.translate: Translate UI
INFO	controlOffset.translate: Translate UI
INFO	controlFiles.translate: Translate UI
INFO	menuObject.translate: Translating Menu
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	menuObject.gsc: Keyboard shortcuts
INFO	viewMain.set_title: Set new title text
DEBUG	viewMain.translate: previous panel size: (877, 797), previous window size: (877, 850)
DEBUG	viewMain.translate: minimum panel size is: (877, 797)
DEBUG	viewMain.translate: new panel size is: (877, 797), new window size is: (877, 850)
```
And tilecutter.config:

```{
    "OFFSET_NEGATIVE_ALLOWED": false,
    "debug_level": 2,
    "debug_on": true,
    "default_image_path": "",
    "default_language": "English",
    "default_paksize": 64,
    "last_image_path": "",
    "last_save_path": "",
    "logfile": "/home/matthew/.tilecutter/tilecutter.log",
    "logfile_platform_default": true,
    "negative_offset_allowed": false,
    "path_to_makeobj": "",
    "transparent": [
        231,
        255,
        255
    ],
    "transparent_bg": [
        [
            153,
            153,
            153
        ],
        [
            103,
            103,
            103
        ]
    ],
    "valid_image_extensions": [
        ".png"
    ],
    "window_maximised": false,
    "window_position": [
        -1,
        -1
    ],
    "window_size": [
        -1,
        -1
    ],
    "write_dat": true
}
```
